USE USERS;

CREATE TABLE ADMINS (
    AdminID int NOT NULL AUTO_INCREMENT,
    LastName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255),
    Email VARCHAR(255) UNIQUE,
    UserName VARCHAR(255) UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(10) NOT NULL,
    PRIMARY KEY (AdminID),
    CHECK (LENGTH(PhoneNumber) = 10),
    CONSTRAINT CHK_ADMIN_PASSWORDHASH_COMPLEXITY CHECK (LENGTH(PasswordHash) >= 8 AND PasswordHash REGEXP '[0-9]' AND PasswordHash REGEXP '[a-z]' AND PasswordHash REGEXP '[A-Z]' AND PasswordHash REGEXP '[^a-zA-Z0-9]')
);

CREATE TABLE SPONSORS (
    SponsorID INT NOT NULL AUTO_INCREMENT,
    AdminID INT NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255),
    Email VARCHAR(255) UNIQUE,
    UserName VARCHAR(255) UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(10) NOT NULL,
    SponsorCatalog VARCHAR(255),
    SponsorTitle VARCHAR(255),
    PRIMARY KEY (SponsorID),
    FOREIGN KEY (AdminID) REFERENCES ADMINS(AdminID),
    CONSTRAINT FK_SPONSOR_ADMINID 
        FOREIGN KEY (AdminID) REFERENCES ADMINS(AdminID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CHK_SPONSOR_PHONENUMBER 
        CHECK (LENGTH(PhoneNumber) = 10),
    CONSTRAINT CHK_SPONSOR_PASSWORDHASH_COMPLEXITY CHECK (LENGTH(PasswordHash) >= 8 AND PasswordHash REGEXP '[0-9]' AND PasswordHash REGEXP '[a-z]' AND PasswordHash REGEXP '[A-Z]' AND PasswordHash REGEXP '[^a-zA-Z0-9]')
);

CREATE TABLE DRIVERS (
    DriverID INT NOT NULL AUTO_INCREMENT,
    AdminID INT NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    FirstName VARCHAR(255),
    Email VARCHAR(255) UNIQUE,
    UserName VARCHAR(255) UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(10) NOT NULL,
    PRIMARY KEY (DriverID),
    FOREIGN KEY (AdminID) REFERENCES ADMINS(AdminID),
    CONSTRAINT FK_Drivers_Admin FOREIGN KEY (AdminID) REFERENCES ADMINS(AdminID) ON DELETE CASCADE,
    CONSTRAINT CHK_DRIVER_PASSWORDHASH_COMPLEXITY CHECK (LENGTH(PasswordHash) >= 8 AND PasswordHash REGEXP '[0-9]' AND PasswordHash REGEXP '[a-z]' AND PasswordHash REGEXP '[A-Z]' AND PasswordHash REGEXP '[^a-zA-Z0-9]')
);

CREATE TABLE DRIVER_SPONSORS (
    DriverID INT NOT NULL,
    SponsorID INT NOT NULL,
    PRIMARY KEY (DriverID, SponsorID),
    FOREIGN KEY (DriverID) REFERENCES DRIVERS(DriverID) ON DELETE CASCADE,
    FOREIGN KEY (SponsorID) REFERENCES SPONSORS(SponsorID) ON DELETE CASCADE
);

CREATE TABLE POINTS (
    PointsID INT NOT NULL AUTO_INCREMENT,
    DriverID INT NOT NULL,
    PointDate TIMESTAMP NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    Points INT NOT NULL,
    PRIMARY KEY (PointsID),
    FOREIGN KEY (DriverID) REFERENCES DRIVERS(DriverID),
    CHECK (Points >= 0)
);

CREATE TABLE ORDERS (
    OrderID INT NOT NULL AUTO_INCREMENT,
    SponsorID INT NOT NULL,
    DriverID INT NOT NULL,
    PRIMARY KEY (OrderID),
    FOREIGN KEY (SponsorID) REFERENCES SPONSORS(SponsorID),
    FOREIGN KEY (DriverID) REFERENCES DRIVERS(DriverID)
);

CREATE TABLE PRODUCTS (
    ProductID INT NOT NULL AUTO_INCREMENT,
    SponsorID INT NOT NULL,
    Price decimal(10, 2) DEFAULT 0.00,
    Quantity INT DEFAULT 0,
    PRIMARY KEY (ProductID),
    FOREIGN KEY (SponsorID) REFERENCES SPONSORS(SponsorID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);