USE USERS;

DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS POINTS;
DROP TABLE IF EXISTS DRIVERS;
DROP TABLE IF EXISTS DRIVER_SPONSORS;
DROP TABLE IF EXISTS SPONSORS;
DROP TABLE IF EXISTS ADMINS;